const CardDetail = [
  {
    image: "https://picsum.photos/200/300",
    price: "Rs. 4,500",
    details: "Mobile",
    area: "North Nazimabad, Khi",
    date: "26 Sep, 2020",
  },
  {
    image: "https://picsum.photos/300/300",
    price: "Rs. 5,500",
    details: "Cell Phone",
    area: "Nazimabad, Khi",
    date: "2 Sep, 2020",
  },
  {
    image: "https://picsum.photos/400/300",
    price: "Rs. 7,000",
    details: "Mobile",
    area: "North Karachi, Khi",
    date: "26 Sep, 2020",
  },
  {
    image: "https://picsum.photos/300/400",
    price: "Rs. 8,000",
    details: "Mobile",
    area: "North Karachi, Khi",
    date: "26 Sep, 2020",
  },
  {
    image: "https://picsum.photos/250/400",
    price: "Rs. 8,000",
    details: "Mobile",
    area: "North Karachi, Khi",
    date: "26 Sep, 2020",
  },
  {
    image: "https://picsum.photos/350/400",
    price: "Rs. 8,000",
    details: "Mobile",
    area: "North Karachi, Khi",
    date: "26 Sep, 2020",
  },
  {
    image: "https://picsum.photos/450/400",
    price: "Rs. 8,000",
    details: "Mobile",
    area: "North Karachi, Khi",
    date: "26 Sep, 2020",
  },
  {
    image: "https://picsum.photos/550/400",
    price: "Rs. 8,000",
    details: "Mobile",
    area: "North Karachi, Khi",
    date: "26 Sep, 2020",
  },
  {
    image: "https://picsum.photos/650/400",
    price: "Rs. 8,000",
    details: "Mobile",
    area: "North Karachi, Khi",
    date: "26 Sep, 2020",
  },
  {
    image: "https://picsum.photos/750/400",
    price: "Rs. 8,000",
    details: "Mobile",
    area: "North Karachi, Khi",
    date: "26 Sep, 2020",
  },
  {
    image: "https://picsum.photos/850/400",
    price: "Rs. 8,000",
    details: "Mobile",
    area: "North Karachi, Khi",
    date: "26 Sep, 2020",
  },
  {
    image: "https://picsum.photos/950/400",
    price: "Rs. 8,000",
    details: "Mobile",
    area: "North Karachi, Khi",
    date: "26 Sep, 2020",
  },
  {
    image: "https://picsum.photos/110/400",
    price: "Rs. 8,000",
    details: "Mobile",
    area: "North Karachi, Khi",
    date: "26 Sep, 2020",
  },
  {
    image: "https://picsum.photos/120/400",
    price: "Rs. 8,000",
    details: "Mobile",
    area: "North Karachi, Khi",
    date: "26 Sep, 2020",
  },
  {
    image: "https://picsum.photos/160/400",
    price: "Rs. 8,000",
    details: "Mobile",
    area: "North Karachi, Khi",
    date: "26 Sep, 2020",
  },
  {
    image: "https://picsum.photos/180/400",
    price: "Rs. 8,000",
    details: "Mobile",
    area: "North Karachi, Khi",
    date: "26 Sep, 2020",
  },
  {
    image: "https://picsum.photos/690/400",
    price: "Rs. 8,000",
    details: "Mobile",
    area: "North Karachi, Khi",
    date: "26 Sep, 2020",
  },
  {
    image: "https://picsum.photos/780/400",
    price: "Rs. 8,000",
    details: "Mobile",
    area: "North Karachi, Khi",
    date: "26 Sep, 2020",
  },
  {
    image: "https://picsum.photos/990/400",
    price: "Rs. 8,000",
    details: "Mobile",
    area: "North Karachi, Khi",
    date: "26 Sep, 2020",
  },
  {
    image: "https://picsum.photos/130/400",
    price: "Rs. 8,000",
    details: "Mobile",
    area: "North Karachi, Khi",
    date: "26 Sep, 2020",
  },
  {
    image: "https://picsum.photos/420/400",
    price: "Rs. 8,000",
    details: "Mobile",
    area: "North Karachi, Khi",
    date: "26 Sep, 2020",
  },
  {
    image: "https://picsum.photos/440/400",
    price: "Rs. 8,000",
    details: "Mobile",
    area: "North Karachi, Khi",
    date: "26 Sep, 2020",
  },
  {
    image: "https://picsum.photos/460/400",
    price: "Rs. 8,000",
    details: "Mobile",
    area: "North Karachi, Khi",
    date: "26 Sep, 2020",
  },
  {
    image: "https://picsum.photos/880/400",
    price: "Rs. 8,000",
    details: "Mobile",
    area: "North Karachi, Khi",
    date: "26 Sep, 2020",
  },
  {
    image: "https://picsum.photos/660/400",
    price: "Rs. 8,000",
    details: "Mobile",
    area: "North Karachi, Khi",
    date: "26 Sep, 2020",
  },
  {
    image: "https://picsum.photos/840/400",
    price: "Rs. 8,000",
    details: "Mobile",
    area: "North Karachi, Khi",
    date: "26 Sep, 2020",
  },
  {
    image: "https://picsum.photos/480/400",
    price: "Rs. 8,000",
    details: "Mobile",
    area: "North Karachi, Khi",
    date: "26 Sep, 2020",
  },
  {
    image: "https://picsum.photos/540/400",
    price: "Rs. 8,000",
    details: "Mobile",
    area: "North Karachi, Khi",
    date: "26 Sep, 2020",
  },
  {
    image: "https://picsum.photos/670/400",
    price: "Rs. 8,000",
    details: "Mobile",
    area: "North Karachi, Khi",
    date: "26 Sep, 2020",
  },
  {
    image: "https://picsum.photos/180/400",
    price: "Rs. 8,000",
    details: "Mobile",
    area: "North Karachi, Khi",
    date: "26 Sep, 2020",
  },
  // {
  //   image: "https://picsum.photos/230/400",
  //   price: "Rs. 8,000",
  //   details: "Mobile",
  //   area: "North Karachi, Khi",
  //   date: "26 Sep, 2020",
  // },
  // {
  //   image: "https://picsum.photos/230/300",
  //   price: "Rs. 8,000",
  //   details: "Mobile",
  //   area: "North Karachi, Khi",
  //   date: "26 Sep, 2020",
  // },
];

export default CardDetail;
